#!/usr/bin/env bash
set -Eeuo pipefail

if [[ "${1-}" == "--hd" ]]; then
  IN_HD=1
fi

errcho() {
  echo "$@" 1>&2
}

get_streamer() {
  if hash streamlink.exe 1>&2 2>/dev/null; then
    echo "streamlink.exe"
  elif hash streamlink 1>&2 2>/dev/null; then
    echo "streamlink"
  else
    errcho "Can't find streamlink nor streamlink.exe"
    errcho "Exiting..."
    exit 1
  fi
}

get_player() {
  if hash mpv.exe 1>&2 2>/dev/null || mpv 1>&2 2>/dev/null; then
    echo "mpv --vo=null --no-video"
  elif hash vlc.exe 1>&2 2>/dev/null || vlc 1>&2 2>/dev/null; then
    echo "vlc --intf dummy"
  fi
}

play() {
  local streamer player
  streamer="$(get_streamer)"
  if [[ -n "${IN_HD-}" ]]; then
    "$streamer" 'https://www.youtube.com/watch?v=5qap5aO4i9A' 1080p
  else
    player="$(get_player)"
    if [[ -n "$player" ]]; then
      "$streamer" 'https://www.youtube.com/watch?v=5qap5aO4i9A' \
                        360p --player="$player" --quiet
    else
      "$streamer" 'https://www.youtube.com/watch?v=5qap5aO4i9A' 360p
    fi
  fi
}

just_chillin() {
  echo " . . . C H I L L I N . . ."
}

ART=$(cat <<GIRL

⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⠖⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⠃⠀⠀⠀⠀⢀⠏⠀⠀⠙⣦⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣠⠚⠛⠒⠲⢤⣄⣷⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠘⣷⡀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣠⣤⣴⣾⡉⠉⠁⠉⠓⢤⡀⠀⠀⠈⠙⠻⣿⡟⢦⡀⠀⠀⠀⠀⠀⠀⠘⣷⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⡴⠋⠀⠀⠀⠀⠙⢶⡄⠀⠀⠀⠙⣆⠀⠀⠀⠀⠀⠙⠦⠑⠀⠀⠀⠀⠀⠀⠀⠹⣇⠀⠀⠀⠀⠀
⠀⠀⠀⢰⠏⠀⠀⠀⠀⠀⠀⠀⠀⠙⣦⠀⣀⣀⣨⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⠀⠀⠀⠀⠀
⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣯⢥⠤⠴⣾⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⡼⠋⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠙⠎⠷⣿⢿⡅⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⡼⠁⠀⠀⠀⠀⠀⠀⠀⠀⡼⠀⠀⠀⢀⣠⢴⣿⣶⣿⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢰⡇⠀⠀⠀⠀⠀⠀⠀⠰⣢⠀⠀⠀⢠⡏⢠⣿⠟⠉⠤⠌⠹⣧⠀⠀⠀⠀⠀⠀⣠⡖⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢸⣀⡀⠀⣰⢢⡀⠀⠀⠀⢹⣄⠀⠀⢸⠀⣿⡏⠀⠀⠀⠂⠀⣹⡇⠀⡀⠀⠀⢸⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠈⠙⠳⠤⠿⠟⣿⣶⣶⣾⣿⣿⣷⣤⡄⠁⠹⣿⣄⠠⣛⣴⣴⣿⠃⢠⠃⢀⡴⠋⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⣯⡿⣿⣿⣷⡄⠀⠈⠛⠶⠦⠶⠛⠁⢀⡖⢶⡾⠀⠐⠻⠒⠒⠦⣄⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣾⣿⣯⠳⢦⣄⣀⡀⣀⣠⣤⠶⢋⣾⠞⠀⠀⠀⠀⣀⣤⠴⢾⣧⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠰⣿⢿⣿⣿⣿⣿⣿⣶⣿⠇⠉⠁⠀⣀⣴⠟⠉⢠⠆⢀⣴⠞⣻⠃⠀⠀⠈⠳⣄⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣴⣶⣾⣿⣿⣿⡟⣿⣿⣿⡏⣠⠖⠛⣲⠟⠁⠀⣠⢋⣴⠟⠁⣰⠃⠀⠀⠀⠀⠀⠈⠓⢦⡀
⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⢿⢷⠙⠿⡾⢿⡿⠞⠁⣰⠞⠁⠀⠀⡴⢁⣾⠿⠂⢰⠃⠀⠀⠀⠀⠀⠀⠀⢀⡾⠁
⠀⠀⠀⠀⠀⠀⠈⠻⢿⣿⣷⣄⣆⠀⠀⠀⢙⡆⢻⢃⠀⠀⠀⢸⢀⣿⠃⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⣰⠋⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠛⠛⣿⠛⠛⠛⠙⡄⠸⡏⠳⢄⡠⢆⣾⠃⠀⠀⠀⢿⠀⠀⠀⠀⠀⣠⠎⠁⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣇⠀⠀⠀⡇⠀⡟⣦⡀⠀⣼⣯⣲⠿⣖⣦⣸⡀⠀⣀⠴⠋⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⣝⣦⡀⡼⠁⠰⠃⠸⣷⢰⡟⠁⠀⠀⣀⣹⡿⠗⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠙⠛⠻⠦⠴⠇⠻⠿⠷⠒⠚⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

       . . . C H I L L I N . . .

GIRL
)

ART_WIDTH=41
ART_HEIGHT=24

if hash tput; then
  columns=$(tput cols)
  lines=$(tput lines)
  if [[ "$columns" -ge "$ART_WIDTH" ]] && [[ "$lines" -ge "$ART_HEIGHT" ]]; then
    padding=$(echo "($columns - $ART_WIDTH) / 2" | bc)

    printf "%s\n" "$ART" | awk "{print sprintf(\"% ${padding}s\", \"\") \$0}"
  else
    just_chillin
  fi
else
  just_chillin
fi

play

