#!/usr/bin/env bash

RESET=$'\033[0m'

for i in {30..37}; do
  printf "\033[%dm\\\033[%dm\t\033[0m\t\033[%dm\\\033[%dm" $i $i $((i + 60)) $((i + 60))
  printf "\033[0m\n"
  printf "\033[%dm\\\033[%dm\t\033[30m\t\033[%dm\\\033[%dm" $((i + 10)) $((i + 10)) $((i + 70)) $((i + 70))
  printf "\033[0m\n\n"
done

echo
echo -e "\\\033[0m                          - Reset everything"
echo -e "\\\033[39m\\\033[49m                 - Reset color"
echo -e "\\\033[2K                          - Clear line"
echo -e "\\\033[<L>;<C>H or \\\033[<L>;<C>f   - Put the cursor at line L and column C."
echo -e "\\\033[<N>A                        - Move the cursor up N lines"
echo -e "\\\033[<N>B                        - Move the cursor down N lines"
echo -e "\\\033[<N>C                        - Move the cursor forward N columns"
echo -e "\\\033[<N>D                        - Move the cursor backward N columns"
echo -e
echo -e "\\\033[2J                          - Clear the screen, move to (0,0)"
echo -e "\\\033[K                           - Erase to end of line"
echo -e "\\\033[s                           - Save cursor position"
echo -e "\\\033[u                           - Restore cursor position"
echo -e
echo -e "\\\033[4m                          - \033[4mUnderline on$RESET"
echo -e "\\\033[4:2m                        - \033[4:2mDouble underline on$RESET"
echo -e "\\\033[4:3m                        - \033[4:3mWavy underline on$RESET"
echo -e "\\\033[4:4m                        - \033[4:4mDotted underline on$RESET"
echo -e "\\\033[4:5m                        - \033[4:5mDashed underline on$RESET"
echo -e "\\\033[24m                         - Underline off"
echo -e
echo -e "\\\033[9m                          - \033[9mStrikethrough on$RESET"
echo -e "\\\033[29m                         - Strikethrough off"
echo -e
echo -e "\\\033[1m                          - \033[1mBold on$RESET"
echo -e "\\\033[21m                         - Bold off"
