#!/usr/bin/env bash

set -euo pipefail

v() {
  if hash nvim 2>/dev/null; then
    nvim "$@"
  elif hash vim 2>/dev/null; then
    vim "$@"
  else
    vi "$@"
  fi
}

usage() {
  echo "I am trapped in a notes factory"
}

if [ $# -eq 0 ]; then
  v "$(find "$HOME/not/" -type f | fzf --height 20% --reverse)"
  exit
fi

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)

filename=''
title=''
content=''
labels=''
formattedLabels=''

while getopts "hl:t:q:" opt; do
   case $opt in
     h)
       usage
       exit
       ;;
     q)
       content=$OPTARG
       ;;
     l)
       labels=$OPTARG
       ;;
     t)
       title=$OPTARG
       ;;
     *)
       usage
       exit 1
   esac
done

if [[ -z $title ]]; then
  title="Scratch at ${TIME}"
fi

if [[ -n $labels ]]; then
  formattedLabels=" [${labels// /, }]"
fi

filename="$HOME/not/[${DATE}] ${title}${formattedLabels}.md"

mkdir -p "$HOME/not"

if [[ -z $content ]]; then
  v "${filename}"
else
  echo "$content" > "${filename}"
fi
