#!/usr/bin/env bash

set -euo pipefail

mkdir -p "$HOME/notes"

v() {
  if hash nvim > /dev/null 2>&1; then
    nvim "$@"
  elif hash vim > /dev/null 2>&1; then
    vim "$@"
  else
    vi "$@"
  fi
}

usage() {
  echo "I am trapped in a notes factory"
}

if [ $# -eq 0 ]; then
  previewer="cat"
  if hash glow > /dev/null 2>&1; then
    previewer="glow -l --style=auto"
    if hash stty > /dev/null 2>&1; then
      read -r _ columns < <(stty size)
      previewer="$previewer -w '$((columns / 2))'"
    fi
  elif hash bat > /dev/null 2>&1; then
    previewer="bat --color=always --plain"
  fi

  cd "$HOME/notes"

  noteToOpen="$(find . -name '.git' -prune -o -type f -print \
                | cut -c 3- \
                | sort -r \
                | fzf --height 30% --reverse --preview "$previewer {}")"
  v "$noteToOpen"
  exit
fi

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)

filename=''
title=''
content=''
labels=''
formattedLabels=''

while getopts "hl:t:q:" opt; do
   case $opt in
     h)
       usage
       exit
       ;;
     q)
       content=$OPTARG
       ;;
     l)
       labels=$OPTARG
       ;;
     t)
       title=$OPTARG
       ;;
     *)
       usage
       exit 1
   esac
done

if [[ -z $title ]]; then
  title="Scratch at ${TIME}"
fi

if [[ -n $labels ]]; then
  formattedLabels=" [${labels// /, }]"
fi

filename="$HOME/notes/[${DATE}] ${title}${formattedLabels}.norg"

if [[ -z $content ]]; then
  v "${filename}"
else
  echo "$content" > "${filename}"
fi
