#!/usr/bin/env bash

set -CEeuo pipefail

mkdir -p "$HOME/notes"

v() {
  if hash nvim &> /dev/null; then
    nvim "$@"
  elif hash vim &> /dev/null; then
    vim "$@"
  else
    vi "$@"
  fi
}

usage() {
  echo "I am trapped in a notes factory"
}

if [[ $# == 0 ]]; then
  previewer="cat"
  # if hash glow > /dev/null 2>&1; then
  #   previewer="glow -l --style=auto"
  #   if hash stty > /dev/null 2>&1; then
  #     read -r _ columns < <(stty size)
  #     previewer="$previewer -w '$((columns / 2))'"
  #   fi
  if hash bat > /dev/null 2>&1; then
    previewer="bat --color=always --plain --paging never"
  fi

  cd "$HOME/notes"

  noteToOpen="$(find . -name '.git' -prune -o -name '.archive' -prune -o -type f -print \
                | cut -c 3- \
                | sort -r \
                | fzf --height 30% --reverse --preview "$previewer {}")"
  v "$noteToOpen"
  exit
fi

NOT_DATE=${NOT_DATE-$(date +%Y-%m-%d)}
NOT_TIME=${NOT_TIME-$(date +%H:%M:%S)}

filename=''
title=''
content=''
labels=''
formattedLabels=''

while getopts "hsl:t:q:" opt; do
   case $opt in
     h)
       usage
       exit
       ;;
     q)
       content=$OPTARG
       ;;
     l)
       labels=$OPTARG
       ;;
     t)
       title=$OPTARG
       ;;
     s)
       title="Scratch ${NOT_TIME}"
       ;;
     *)
       usage
       exit 1
   esac
done

if [[ -n $labels ]]; then
  formattedLabels=":${labels// /,}"
fi

filename="$HOME/notes/${NOT_DATE}:${title// /_}${formattedLabels}.org"

if [[ -z $content ]]; then
  if ! [[ -f "$filename" ]]; then
    cmd=":e $filename | exec appendbufline(0, 0, \"#+title: $title\") | exec appendbufline(0, 1, \"#+date: <$NOT_DATE>\")"
    v +"$cmd"
  else
    v "$filename"
  fi
else
  echo "$content" > "${filename}"
fi
