#!/usr/bin/env bash
set -Eeuo pipefail

SAVE_CURSOR="\033[s"
RESTORE_CURSOR="\033[u"

printf "%s" "$SAVE_CURSOR"

lastTimeLength=0

while true; do
  time=$(ping "$@" -c 1 | rg "^.*time=(.*$)" -r "\$1")
  printf "${RESTORE_CURSOR}%${lastTimeLength}s"
  lastTimeLength="${#time}"
  printf "${RESTORE_CURSOR}%s" "$time"
  sleep 1
done
