""""""""""""""""""""""""""""""""
"          Vim Plug            "
""""""""""""""""""""""""""""""""
call plug#begin()

" Plug 'snoe/nvim-parinfer.js', { 'do': ':UpdateRemotePlugins' }
" Plug 'vim-syntastic/syntastic'
Plug '1995eaton/vim-better-javascript-completion'
Plug 'Raimondi/delimitMate'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimfiler.vim'
Plug 'airblade/vim-gitgutter'
Plug 'benmills/vimux'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'easymotion/vim-easymotion'
Plug 'fatih/vim-go'
Plug 'fleischie/vim-styled-components'
Plug 'guns/vim-clojure-highlight'
Plug 'guns/vim-clojure-static'
Plug 'guns/vim-sexp'
Plug 'janko-m/vim-test'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'jonhiggs/vim-readline'
Plug 'junegunn/goyo.vim'
Plug 'justinmk/vim-sneak'
Plug 'luochen1990/rainbow'
Plug 'matze/vim-move'
Plug 'mitermayer/vim-prettier', { 'do': 'yarn install', 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql'] }
Plug 'morhetz/gruvbox'
Plug 'neovim/node-host', {'do' : 'npm install'}
Plug 'rbgrouleff/bclose.vim'
Plug 'rhysd/vim-crystal'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'sheerun/vim-polyglot'
Plug 'simnalamburt/vim-mundo'
Plug 'stephpy/vim-yaml'
Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }
Plug 'terryma/vim-multiple-cursors'
Plug 'tmux-plugins/vim-tmux'
Plug 'tmux-plugins/vim-tmux-focus-events'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fireplace'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-salve'
Plug 'tpope/vim-sexp-mappings-for-regular-people'
Plug 'tpope/vim-surround'
Plug 'venantius/vim-cljfmt'
Plug 'venantius/vim-eastwood'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'vim-scripts/VimClojure'
Plug 'w0rp/ale'

call plug#end()


""""""""""""""""""""""""""""""""
"         Vim Config           "
""""""""""""""""""""""""""""""""

syntax on
filetype on

set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=indent,eol,start
set backupcopy=yes                                           " see :help crontab
set clipboard=unnamed                                        " yank and paste with the system clipboard
set cursorline
set directory-=.                                             " don't store swapfiles in the current directory
set encoding=utf-8
set expandtab                                                " expand tabs to spaces
set hidden
set hlsearch
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set laststatus=2                                             " always show statusline
set linebreak
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫
set mouse=a                                                  " use mouse everywhere
set number                                                   " show line numbers
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=2                                             " normal mode indentation commands use 2 spaces
set showbreak=+++
set showcmd
set showmatch                                                " highlight matching [{()}]
set smartcase                                                " case-sensitive search if any caps
set softtabstop=2                                            " insert mode tab and backspace use 2 spaces
set splitbelow
set splitright
set t_Co=256
set tabstop=2                                                " actual tabs occupy 8 characters
set textwidth=80
set timeoutlen=500
set undodir=$HOME/.config/nvim/undo                          " where to save undo histories
set undofile                                                 " save undo's after file closes
set undolevels=1000                                          " how many undos
set undoreload=10000                                         " number of lines to save for undo
set visualbell
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc " ignore these folders
set wildmenu
set wildmode=full

hi StatusLine ctermbg=238 ctermfg=234
hi WildMenu ctermbg=27 ctermfg=white

" md is markdown
autocmd BufRead,BufNewFile *.md set filetype=markdown
autocmd BufRead,BufNewFile *.md set spell

" gs is Javascript
autocmd BufRead,BufNewFile *.gs set filetype=javascript

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" Fix Cursor in TMUX
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif


""""""""""""""""""""""""""""""""
"         Vim Mapping          "
""""""""""""""""""""""""""""""""

" space is my leader
map     <space> <leader>

" in case you forgot to sudo
cnoremap w!! %!sudo tee > /dev/null %

" Don't copy the contents of an overwritten selection.
vnoremap p "_dP

" Split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" New Splits
nmap <leader>= :vsp<cr>
nmap <leader>- :sp<cr>

" Redo
nnoremap U <C-R>

" Jump to beginning and end of the line
nnoremap <leader>h ^
nnoremap <leader>l $

" Move up and down even on wrapped line
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" Toggle Wrap
nnoremap <leader>wr :set wrap!<CR>

" Add new line without going to insert mode
nmap <leader>o o<Esc>
nmap <leader>O O<Esc>

" Insert new line at cursor
nmap <leader><CR> i<CR><ESC>

" Use kj as Escape
inoremap kj <esc>

" Save
nnoremap <leader>w :w<CR>

" Quit
nnoremap <leader>q :q<CR>

" Clear search
nnoremap <leader>sc :let @/ = ""<CR>


""""""""""""""""""""""""""""""""
"       Plugins Config         "
""""""""""""""""""""""""""""""""

" Gruvbox
let g:gruvbox_contrast_dark=''
silent colorscheme gruvbox
set background=dark

" Set vimfiler as default
let g:vimfiler_as_default_explorer = 1

" NerdCommenter
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let NERDCreateDefaultMappings=0

" Disable sexp default for leader w
let g:sexp_mappings={
      \'sexp_round_head_wrap_element': ''
      \}

" GitGutter
set updatetime=250

" Deoplete
let g:deoplete#enable_at_startup = 1
if !exists('g:deoplete#omni#input_patterns')
  let g:deoplete#omni#input_patterns = {}
endif
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif

" deoplete tab-complete
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

" omnifuncs
augroup omnifuncs
  autocmd!
  autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
  autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
  autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
  autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
augroup end

" tern
if exists('g:plugs["tern_for_vim"]')
  let g:tern_show_argument_hints = 'on_hold'
  let g:tern_show_signature_in_pum = 1
  autocmd FileType javascript setlocal omnifunc=tern#Complete
  autocmd FileType javascript nnoremap <silent> <buffer> gb :TernDef<CR>
endif

""" Airline Stuff
let g:airline_powerline_fonts = 1
let g:airline_theme='raven'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#whitespace#mixed_indent_algo = 1
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''


" Activate Rainbow parens only for Clojure
autocmd FileType clojure :RainbowToggleOn

" Vim-go
let g:go_fmt_command = "goimports"

" Prettier
let g:prettier#config#trailing_comma = 'es5'
let g:prettier#config#semi = 'false'
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#autoformat = 0
" autocmd BufWritePre *.js,*.json,*.css,*.scss,*.less,*.graphql PrettierAsync

" vim-move
let g:move_key_modifier = 'C'

" keyboard shortcut
nnoremap <leader>a :Ag<space>
nnoremap <leader>d :VimFilerExplorer<CR>
nnoremap <leader>g :GitGutterToggle<CR>

" plugin settings
let g:ctrlp_match_window = 'order:ttb,max:20'
let g:NERDSpaceDelims=1

if executable('fd')
  let g:ctrlp_user_command = 'fd --type f --color=never "" %s'
  let g:ctrlp_use_caching = 0
endif

""" Key Map CtrlP Start

" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg)$',
\}

" Use the nearest .git directory as the cwd
" This makes a lot of sense if you are working on a project that is in version
" control. It also supports works with .svn, .hg, .bzr.
let g:ctrlp_working_path_mode = 'r'

" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>

" Easy bindings for its various modes
nmap <leader>b :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>

""" Key Map CtrlP End

""" Key map BufferGattor Start

" Use the right side of the screen
let g:buffergator_viewport_split_policy = 'R'

" I want my own keymappings...
let g:buffergator_suppress_keymaps = 1

" Looper buffers
"let g:buffergator_mru_cycle_loop = 1

" Go to the previous buffer open
nmap <leader>j :BuffergatorMruCyclePrev<cr>

" Go to the next buffer open
nmap <leader>k :BuffergatorMruCycleNext<cr>

" View the entire list of buffers open
nmap <leader>bl :BuffergatorOpen<cr>

" Open new buffer
nmap <leader>t :enew<cr>

" Close buffer
nmap <leader>bc :bp <BAR> bd #<cr>

""" Key map BufferGattor End

" Toggle gundo (better undo)
nnoremap <leader>u :MundoToggle<CR>

" Easymotion
map <leader><space> <Plug>(easymotion-prefix)
map <Plug>(easymotion-prefix)<space> <Plug>(easymotion-bd-w)

" Goyo toggling
nnoremap <leader>ff :Goyo<CR>

" Sneak keep searching with s
let g:sneak#s_next = 1

" The only mapping I care about from NerdCommenter
map <leader>cc <plug>NERDCommenterToggle 

" Run test for golang
autocmd FileType go nnoremap <buffer> <leader>T :GoTest<CR>

" vim-test
let test#strategy = "vimux" " Run test in tmux window 
